/**
 * This software is released under the terms of the MIT License
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * @copyright  2009-2011 Roberto Perpuly
 * @license    http://www.opensource.org/licenses/mit-license.php The MIT License
 */
#ifndef __FINDINFFILESFEATURECLASS_H__
#define __FINDINFFILESFEATURECLASS_H__

/**
@file
Subclass of FindInFilesPanelGeneratedClass, which is generated by wxFormBuilder.
*/

#include <features/wxformbuilder/FindInFilesFeatureForms.h>
#include <features/BackgroundFileReaderClass.h>
#include <search/DirectorySearchClass.h>
#include <search/FindInFilesClass.h>
#include <globals/ProjectClass.h>
#include <widgets/ComboBoxHistoryClass.h>
#include <widgets/NotebookClass.h>
#include <widgets/StatusBarWithGaugeClass.h>
#include <features/FeatureClass.h>
#include <wx/thread.h>
#include <wx/object.h>
#include <vector>

namespace t4p {

/**
 * A single hit that resulted from a find in files action.
 */
class FindInFilesHitClass : public wxObject {

	DECLARE_DYNAMIC_CLASS(t4p::FindInFilesHitClass)


public:

	/**
	 * the full path of the file searched
	 */
	wxString FileName;
	
	/**
	 * preview is the entire line where the hit occurred.
	 */
	wxString Preview;
	
	/**
	 * line where the hit was found (1- based)
	 */
	int LineNumber;
	
	/**
	 * character position where the hit was found (0- based),
	 * relative to the start of the line.
	 * 
	 * 0 <= LineOffset < Preview.Length()
	 */
	int LineOffset;
	
	/**
	 * character position where the hit was found (0- based)
	 * relative to the beginning of the file.
	 */
	int FileOffset;
	
	/**
	 * Character length of the matching hit
	 */
	int MatchLength;

	FindInFilesHitClass();

	/**
	 * This will fully clone hit. Deep copy makes assignment thread-safe because by default
	 * wxStrings are shallow-cloned.
	 * @param hit to deep copy
	 */
	FindInFilesHitClass(const t4p::FindInFilesHitClass& hit);

	/**
	 * All parameters will be deep copied. Deep copy makes assignment thread-safe because by default
	 * wxStrings are shallow-cloned.

	 * @param fileName the full path to the file
	 * @param preview the contents of the line where the hit ocurred
	 * @param lineNumber line (1 based) where the hit 
	 * @param lineOffset character position (0 based) where the hit ocurred. relative to the line
	 * @param fileOffset character position (0 based) where the hit ocurred, relative to the beginning
	 *        of the file
	 * @param matchLength length of the matching text
	 */
	FindInFilesHitClass(const wxString& fileName, const wxString& preview, int lineNumber, int lineOffset, 
		int fileOffset, int matchLength);

	/**
	 * This will fully clone hit. Deep copy makes assignment thread-safe because by default
	 * wxStrings are shallow-cloned.
	 * @param hit to deep copy
	 */
	FindInFilesHitClass& operator=(const t4p::FindInFilesHitClass& hit);
	
	/**
	 * Equality operator, needed to implment wxVariant stuff
	 * @param bool return if hits are the same
	 */
	bool operator==(const t4p::FindInFilesHitClass& hit);

	/**
	 * This will fully clone hit. Deep copy makes assignment thread-safe because by default
	 * wxStrings are shallow-cloned.
	 * @param hit to deep copy
	 */
	void Copy(const t4p::FindInFilesHitClass& src);
};

DECLARE_VARIANT_OBJECT(t4p::FindInFilesHitClass)

/**
 * One EVENT_FIND_IN_FILES_FILE_HIT event will be generated once an entire file has been searched.
 */
class FindInFilesHitEventClass : public wxEvent {

public:

	/**
	 * @param id of the event, used to differentiate between multiple searches if they are happpening
	 *        simultaneously
	 * @param hits the hits found.  this vector will be deep copied.
	 */
	FindInFilesHitEventClass(int eventId, const std::vector<t4p::FindInFilesHitClass>& hits);

	wxEvent* Clone() const;

	/**
	 * @return vector of All of the hits for a single file.
	 */
	std::vector<t4p::FindInFilesHitClass> GetHits() const;

private:

	/**
	 * All of the hits for a single file. Hiding this vector because we want to make sure
	 * it is deep copied every time since we this event will be handled
	 * by multiple threads.
	 */
	std::vector<t4p::FindInFilesHitClass> Hits;

};


const wxEventType EVENT_FIND_IN_FILES_FILE_HIT = wxNewEventType();

typedef void (wxEvtHandler::*FindInFilesHitEventClassFunction)(FindInFilesHitEventClass&);

#define EVT_FIND_IN_FILES_HITS(id, fn) \
	DECLARE_EVENT_TABLE_ENTRY(t4p::EVENT_FIND_IN_FILES_FILE_HIT, id, -1, \
    (wxObjectEventFunction) (wxEventFunction) \
    wxStaticCastEvent( FindInFilesHitEventClassFunction, & fn ), (wxObject *) NULL ),


/**
 * This class is the background thread where all finding and replacing will be done.
 */
class FindInFilesBackgroundReaderClass: public BackgroundFileReaderClass {
public:

	/**
	 * @param wxEvtHandler This object will receive the EVENT_FIND_IN_FILES_FILE_HIT events.
	 *        and the EVENT_WORK_* events
	 */
	FindInFilesBackgroundReaderClass(t4p::RunningThreadsClass& runningThreads, int eventId);

	/**
	 * Prepare to iterate through all files in the given directory.
	 * 
	 * @param FindInFilesClass findInFiles the expression to search for
	 * @param doHiddenFiles if TRUE then hidden files are searched
	 * @param skipFiles full paths of files to not search. We want to NOT perform searches 
	 *        in files that are already opened; those would result in incorrect hits.
	 * @return True if directory is valid and the find expression is valid.
	 */
	bool InitForFind(FindInFilesClass findInFiles, bool doHiddenFiles, std::vector<wxString> skipFiles);

	/**
	 * When replacing, the thread will replace the files in the given hits. In case files are opened, we don't want to
	 * replace them in the background since the user may have modified them but not saved them yet.
	 * 
	 * @param FindInFilesClass findInFiles the expression to search and replace with
	 * @param allHits the files to perform replacements in.
	 * @param skipFiles full paths of files to not replace. We want to NOT perform replacements
	 * in files that are already opened.
	 * @return true if hits is not empty
	 */
	bool InitForReplace(FindInFilesClass findInFiles, const std::vector<wxString>& replaceFiles, std::vector<wxString> skipFiles);

	/**
	 * Creates a Hit event for the current FindInFiles match. (the event will NOT be posted).
	 * @param lineNumber the line that where the hit occurred
	 * @param the line text itself
	 * @param fileName the name of the file that was searched.
	 */
	static wxCommandEvent MakeHitEvent(int lineNumber, const wxString& lineText, const wxString& fileName);

	wxString GetLabel() const;

protected:

	/**
	 * Finds the expression in all files.
	 */
	bool BackgroundFileRead(DirectorySearchClass& search);

	/**
	 * Replaces this expression in all files.
	 */
	bool BackgroundFileMatch(const wxString& file);
	
private:

	/**
	 * To find matches in files.
	 * 
	 * @var FindInFilesClass
	 */
	FindInFilesClass FindInFiles;
	
	/**
	 * Matched files that will NOT be replaced / searched
	 * The feature will make the background thread skip the files that are currently opened; this way the result do not
	 * show stale (and possibly wrong) hits
	 */
	std::vector<wxString> SkipFiles;
};

/** Implementing FindInFilesPanelGeneratedClass */
class FindInFilesResultsPanelClass : public FindInFilesResultsPanelGeneratedClass {
protected:
	// Handlers for FindInFilesResultsPanelClass events.
	void OnReplaceButton(wxCommandEvent& event);
	void OnReplaceAllInFileButton(wxCommandEvent& event);
	void OnReplaceInAllFilesButton(wxCommandEvent& event);
	void OnFileHit(t4p::FindInFilesHitEventClass& event);
	void OnStopButton(wxCommandEvent& event);
	void OnRowActivated(wxDataViewEvent& event);
	void OnCopySelectedButton(wxCommandEvent& event);
	void OnCopyAllButton(wxCommandEvent& event);
	void OnFindInFilesComplete(wxCommandEvent& event);
	void OnNextHitButton(wxCommandEvent& event);
	void OnPreviousHitButton(wxCommandEvent& event);
	void OnRegExReplaceHelpButton(wxCommandEvent& event);
	void OnReplaceTextEnter(wxCommandEvent& event);

		
public:

	/**
	 * Construct a new FindInFilesResultsPanelClass 
	 * 
	 * @param wxWindow* parent the parent window
	 * @param NotebookClass* notebook the object that holds the text. The pointer will NOT be managed (deleted) by this class. 
	 * @param StatusBarWithGaugeClass* gauge the object used to create gauge for showing progress. The pointer will NOT be managed 
	 *        (deleted) by this class. 
	 * @param runningThreads manages the background search thread
	 */
	FindInFilesResultsPanelClass(wxWindow* parent, NotebookClass* notebook, StatusBarWithGaugeClass* gauge,
		t4p::RunningThreadsClass& runningThreads);
	
	~FindInFilesResultsPanelClass();
	
	/**
	 * Start a file search.
	 * 
	 * @param FindInFilesClass findInFiles the search expression
	 * @param wxString path the directory to search in
	 * @param bool if TRUE then hidden files will be searched
	 */
	void Find(const FindInFilesClass& findInFiles, bool doHiddenFiles);
	
	/**
	 * Stops a currently running search. It will clean up 
	 * the gauge also, this means that it must be called while the gauge is valid (ie NOT
	 * at program end)
	 */
	void Stop();

	/**
	 * Move the cursor to the next find in files match.
	 * Will set the cursor to the position of the match, opening the file
	 * it if it's not already open.
	 */
	void ShowNextMatch();
	
	/**
	 * Move the cursor to the previous find in files match.
	 * Will set the cursor to the position of the match, opening the file
	 * it if it's not already open.
	 */
	void ShowPreviousMatch();

private:

	/**
	 * To find matches in files.
	 * 
	 * @var FindInFilesClass
	 */
	FindInFilesClass FindInFiles;

	/**
	 * The matches (results of the find)
	 */
	std::vector<t4p::FindInFilesHitClass> AllHits;

	/**
	 * keeps track of the background thread
	 */
	t4p::RunningThreadsClass& RunningThreads;
		
	/**
	 * To open the files 
	 * @var NotebookClass
	 */
	NotebookClass* Notebook;
	
	/**
	 * To display status bar to the user
	 * @var StatusBarWithGaugeClass
	 */
	StatusBarWithGaugeClass* Gauge;
	
	/**
	 * The number of files that contained at least one match.
	 * 
	 * @var int
	 */
	int MatchedFiles;

	/**
	 * The unique identifier for the gauge.
	 */
	int FindInFilesGaugeId;

	/**
	 * to stop the find in in files action if this panel is closed.
	 */
	int RunningActionId;

	/**
	 * Need to save the insertion point of the replace combo boxes; in Win32
	 * GetInsertionPoint() of combobox fails when it does not have focus.
	 * The insertion is needed to have the cursor show up properly when
	 * the user clicks on the regex help buttons
	 */
	int CurrentInsertionPointReplace;
	
	/**
	 * Enable the controls that allow the user to replace hits or stop searches.
	 * 
	 * @param bool enableStopButton if true, the stop button is enabled, else it is disabled
	 * @param bool enableReplaceButtons if true, the replace buttons are enabled, else they are disabled
	 * @param bool enableCopyButtons if true the copy to clipboard buttos are enabled, else they are disabled
	 */
	void EnableButtons(bool enableStopButton, bool enableReplaceButtons, bool enableCopyButtons);

	/**
	 * Place the given string in the results status label
	 * 
	 * @param wxString message to show to the user
	 */
	void SetStatus(const wxString& status);
			
	/**
	 * Retutns the number of files that had matches. 
	 * 
	 * @return int the number of files under FindPath that had at least one match for this Expression
	 */
	int GetNumberOfMatchedFiles();
	
	/**
	 * Timer handler.
	 * 
	 * @param t4p::ActionProgressEventClass& event
	 */
	 void OnActionProgress(t4p::ActionProgressEventClass& event);

	 /**
	  * Search in the files that are opened. We want to do this so that we only show the most up-to-date
	  * hits
	  */
	 void FindInOpenedFiles();

	/**
 	 * Shows the i'th match. Will set the cursor to the position of the match, opening the file
	 * it if it's not already open.
	 *
	 * @param i index of hit to show. i is 0-based
	 */
	void ShowMatch(int i);
	
	/**
 	 * Shows the i'th match. Will set the cursor to the position of the match, opening the file
	 * it if it's not already open. Additionally, it will scroll the ith match into
	 * view.  This is useful when the user cycles through the matches with the keyboard
	 * shortcut; the proper match is selected and shown into view
	 *
	 * @param i index of hit to show. i is 0-based
	 */
	void ShowMatchAndEnsureVisible(int i);

	void OnActionComplete(t4p::ActionEventClass& event);

	/**
	 * handling of the replace regex help menu
	 */
	void InsertReplaceRegExSymbol(wxCommandEvent& event);
	
	/**
	 * Need to save the insertion point of the Find and replace combo boxes; in Win32
	 * GetInsertionPoint() of combobox fails when it does not have focus.
	 * The insertion is needed to have the cursor show up properly when
	 * the user clicks on the regex help buttons
	 */
	void OnKillFocusReplaceText(wxFocusEvent& event);
	
	DECLARE_EVENT_TABLE()
};

class FindInFilesFeatureClass : public FeatureClass {

public:
	
	/**
	 * Holds previously entered searches. We need these to persist longer than the dialog so that
	 * the user's inputs are saved.
	 */
	ComboBoxHistoryClass FindHistory;
	
	/**
	 * Holds previously entered replacements. We need these to persist longer than the dialog so that
	 * the user's inputs are saved.
	 */
	ComboBoxHistoryClass ReplaceHistory;

	/**
	 * Holds previously entered directories to search in. We need these to persist longer than the dialog so that
	 * the user's inputs are saved.
	 */
	ComboBoxHistoryClass DirectoriesHistory;
	
	/**
	 * Holds previously entered file filters. We need these to persist longer than the dialog so that
	 * the user's inputs are saved.
	 */
	ComboBoxHistoryClass FilesHistory;
	
	/**
	 * We will NOT use this object to actually search, we will just use this to keep track of the last
	 * inputs by the user so we can show them
	 *
	 */
	FindInFilesClass PreviousFindInFiles;

	/**
	 * If TRUE, hidden files are searched
	 */
	bool DoHiddenFiles;

	/**
	 * Constructor
	 */
	FindInFilesFeatureClass(t4p::AppClass& app);
	
	/**
	 * Add menu items to the search menu for this feature.
	 * 
	 * @param wxMenu* menu the tools menu to add items to.
	 */
	void AddSearchMenuItems(wxMenu* searchMenu);

	void AddKeyboardShortcuts(std::vector<DynamicCmdClass>& shortcuts);

private:
	
	/**
	 * show the find dialog 
	 */
	void OnEditFindInFiles(wxCommandEvent& event);

	void OnEditFindInFilesNext(wxCommandEvent& event);

	void OnEditFindInFilesPrevious(wxCommandEvent& event);
	
	/**
	 * When a tools notebook tab is closed, if its a find in files results tab
	 * the the search will be stopped AND the gauge must be cleaned up.
	 */
	void OnToolsNotebookPageClosed(wxAuiNotebookEvent& event);
	
	/**
	 * Safer to keep a pointer to these, rather than attempt to type cast.
	 * Because the tools notebook can contain many types of panels.
	 * When a tools notebook tab is closed, if its a find in files results tab
	 * the the search will be stopped AND the gauge must be cleaned up.
	 * Note that because these are window pointers, we wont own the pointers
	 * wxWidgets will clean them up.
	 */
	std::vector<t4p::FindInFilesResultsPanelClass*> ResultsPanels;
	
	DECLARE_EVENT_TABLE()
};

class FindInFilesDialogClass: public FindInFilesDialogGeneratedClass {
	
public:

	FindInFilesDialogClass(wxWindow* parent, FindInFilesFeatureClass& feature);

protected:

	virtual void OnOkButton(wxCommandEvent& event);
	virtual void OnCancelButton(wxCommandEvent& event);
	void OnRegExFindHelpButton(wxCommandEvent& event);
	void OnRegExReplaceHelpButton(wxCommandEvent& event);
	void OnDirChanged(wxFileDirPickerEvent& event);

private:

	FindInFilesFeatureClass& Feature;

	int CurrentInsertionPointFind;

	int CurrentInsertionPointReplace;
	
	/** 
	 * since this panel handles EVT_TEXT_ENTER, we need to handle the
	 * tab traversal ourselves otherwise tab travesal wont work
	 */
	void OnKeyDown(wxKeyEvent& event);
	
	/**
	 * Need to save the insertion point of the Find and replace combo boxes; in Win32
	 * GetInsertionPoint() of combobox fails when it does not have focus.
	 * The insertion is needed to have the cursor show up properly when
	 * the user clicks on the regex help buttons
	 */
	void OnKillFocusFindText(wxFocusEvent& event);
	void OnKillFocusReplaceText(wxFocusEvent& event);

	/**
	 * handle the regular expression popup menu. Will add the symbol
	 * the the expression textbox value.
	 */
	void InsertRegExSymbol(wxCommandEvent& event);

	/**
	 * handle the regular expression replace popup menu. Will add the symbol
	 * the the replace textbox value.
	 */
	void InsertReplaceRegExSymbol(wxCommandEvent& event);

	DECLARE_EVENT_TABLE()
};

}
#endif // __FINDINFFILESFEATURECLASS_H__
