/**
 * This software is released under the terms of the MIT License
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * @copyright  2009-2011 Roberto Perpuly
 * @license    http://www.opensource.org/licenses/mit-license.php The MIT License
 * @author     $Author: robertop2004@gmail.com $
 * @date       $Date: 2011-06-10 17:19:31 -0700 (Fri, 10 Jun 2011) $
 * @version    $Rev: 555 $ 
 */
#ifndef __WebBrowserPanelClass__
#define __WebBrowserPanelClass__

/**
@file
Subclass of WebBrowserPanelGeneratedClass, which is generated by wxFormBuilder.
*/
#include <plugins/wxformbuilder/WebBrowserPanelGeneratedClass.h>
#include <PluginClass.h>

namespace mvceditor {
	
/** Implementing WebBrowserPanelGeneratedClass */
class WebBrowserPanelClass : public WebBrowserPanelGeneratedClass {
protected:
	// Handlers for WebBrowserPanelGeneratedClass events.
	void OnGoButton(wxCommandEvent& event);

public:
	/** Constructor */
	WebBrowserPanelClass(wxWindow* parent, StatusBarWithGaugeClass* statusBarWithGauge);
	
	/**
	 * Set the URL
	 * 
	 * @param wxString url the URL to load
	 */
	void SetUrl(const wxString& url);
	
private:

	/**
	 * Called when the URL is going to be loaded
	 */
	void OnInitUrl(wxWebEvent& event);
	
	/**
	 * Called when the URL has finished loading and page has been fully rendered
	 */	
	void OnDomContentLoaded(wxWebEvent& event);
	
	/**
	 * When a new page is browsed, change the Url input
	 */
	void OnLocationChange(wxWebEvent& event);
	
	/**
	 * Update the status bar with the latest info on the web browser loading process.
	 * 
	 * @param wxWebEvent& event
	 */
	void OnStateChange(wxWebEvent& evt);

	/**
	 * wxEVT_WEB_STATUSCHANGE is received when the status text changes when a web page is loading. For example, the 
	 * IP is being looked up in DNS, the content is loading, etc..
	 * 
	 * @param wxWebEvent& event
	 */
	void OnStatusChange(wxWebEvent& evt);
	
	/**
	 * wxEVT_WEB_STATUSTEXT is received when somebody hovers the mouse over a link and the status text should be updated
	 * 
	 * @param wxWebEvent& event
	 */
	void OnStatusText(wxWebEvent& evt);
	
	/**
	 * Pulse the gauge on every timer tick.
	 * 
	 * @param wxTimerEvent& the event
	 */
	void OnTimer(wxTimerEvent& event);
	
	/**
	 * To show status to the user
	 * 
	 * @var StatusBarWithGaugeClass*
	 */
	 StatusBarWithGaugeClass* StatusBarWithGauge;
	 
	 /**
	  * We will use this timer update the gauge every > 100ms so that the gauge animation looks smooth
	  * 
	  * @var wxTimer
	  */
	wxTimer Timer;
	
	static const int TIMER_INTERVAL = 100;
	 
	 DECLARE_EVENT_TABLE()
	 
};

class WebBrowserPluginClass : public PluginClass {

public:
	/**
	 * Constructor
 	 */
	WebBrowserPluginClass();
	
	/**
	 * Add menu items
	 */
	virtual void AddToolsMenuItems(wxMenu* toolsMenu);

private:

	/**
	 * Menu item handler.  Will create a new web browser window.
	 * 
	 * @param wxCommandEvent& event 
	 */
	void OnRunInBrowser(wxCommandEvent& event);
	
	/**
	 * initialize the web browser
	 */
	bool InitializeXulRunner();
	
	/**
	 * The menu item 
	 */	
	wxMenuItem* RunBrowserMenuItem;
	
	/**
	 * Flag to make sure we do not initialize webconnect control more than once
	 */
	bool XulRunnerInitialized;
	
	/**
	 * Flag that tells us whether XULRunner has been found and the web browser will work
	 */
	bool XulRunnerGood;
	
	DECLARE_EVENT_TABLE()
		
};

}
#endif // __WebBrowserPanelClass__
